# Generated by Django 5.0.6 on 2024-05-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_rel_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('enrollment_year', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
